version: '3.8'

services:
  app:
    build: .
    container_name: vendo_user_service_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:16
    container_name: vendo_user_service_postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
   