version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: vendo_user_service_postgres_development
    env_file:
      - .env
    ports:
      - "5432:5432"  # Host port:Container port
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev_network

volumes:
  postgres_data:

networks:
  dev_network:
